#config/facebook.yml

app_id: '157680634273999'
api_key: '5041bf0379d049c993576818ca8acbc6'
app_secret: '7342da07acdd457a66f094a8bce9cef7'
perms: 'email,read_mailbox,user_photos,user_notes,user_events,user_birthday,friends_birthday,friends_events,user_relationships,publish_stream,offline_access'

