#config/twitter.yml

api_key: "ILqxL7tNcxxMHsWNDOySQ"
oauth_token: "dtx5vi1uvpJAgFK2G7qehKycUaObDZPVYAzGNznV"
oauth_secret: "tOPkGcjCKSUJdxEfzS0jnDQuKnjmWChtxKouSvIDDJw"
consumer_token: "ILqxL7tNcxxMHsWNDOySQ"
consumer_secret: "h8i3N7dypdJbvbPgYpmvcfCsm05Bc7fi108InTJhSoU"
site: "http://api.twitter.com"
authorize_path: "/oauth/request_token"

